module.exports = {
    '@api': './src/api',
    '@assets': './src/assets',
    '@components': './src/components',
    '@config': './src/config',
    '@pages': './src/pages',
    '@partials': './src/partials',
    '@redux': './src/redux',
    '@redux-articles': './src/redux/redux-articles',
    '@redux-locale': './src/redux/redux-locale',
    '@redux-oauth': './src/redux/redux-oauth',
    '@redux-projects': './src/redux/redux-projects',
    '@socket': './src/socket',
    '@styles': './src/styles',
};
