const NAME_SPACE = '@redux-articles';

export const LOAD_ARTICLES_REQUEST = `${NAME_SPACE}/LOAD_ARTICLES_REQUEST`;
export const LOAD_ARTICLES_SUCCESS = `${NAME_SPACE}/LOAD_ARTICLES_SUCCESS`;
export const LOAD_ARTICLES_ERROR = `${NAME_SPACE}/LOAD_ARTICLES_ERROR`;
