const NAME_SPACE = '@redux-projects';

export const LOAD_PROJECTS_REQUEST = `${NAME_SPACE}/LOAD_PROJECTS_REQUEST`;
export const LOAD_PROJECTS_SUCCESS = `${NAME_SPACE}/LOAD_PROJECTS_SUCCESS`;
export const LOAD_PROJECTS_ERROR = `${NAME_SPACE}/LOAD_PROJECTS_ERROR`;
